"""empty message

Revision ID: 252fa62beb14
Revises: 5f787c84a554
Create Date: 2020-06-19 12:48:50.939048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252fa62beb14'
down_revision = '5f787c84a554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'descripcion',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'descripcion',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
