"""empty message

Revision ID: cb5fcad42ce6
Revises: 
Create Date: 2020-06-15 17:32:02.225508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5fcad42ce6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_factura_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usuario_factura_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detallefactura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productos_comprados', sa.String(length=100), nullable=False),
    sa.Column('factura_id', sa.String(length=100), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detallefactura')
    op.drop_table('factura')
    op.drop_table('user')
    op.drop_table('productos')
    # ### end Alembic commands ###
